Re-former
AbdelrhmanAmin/reformer pull request #1
Opened 2021-01-05 18:07 UTC by AbdelrhmanAmin

In this project, I've created a simple form to save user data
-validations
-associations
-controllers
-Delete
-New
-Edit

2021-01-05 18:33 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

* [ ] There should be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

- [ ] check the rest below 👇 

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-05 18:33 UTC, Spayco commented on app/controllers/users_controller.rb
> +    else
* [ ] `redirect_to new_user_path` if user was saved ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_create.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

2021-01-05 18:33 UTC, Spayco commented on app/controllers/users_controller.rb
> +      redirect_to root_path
* [ ] `redirect_to edit_user_path` if user was saved

2021-01-06 01:06 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Abdo Amin Amin** 
Excellent job following the instruction of the previous TSE :muscle:  :muscle:
Your page meets most of the requirements :clap: :clap: :clap:  
Just one last details before you can go ahead:

- [ ] Add a screenshot to the README file 
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-01-06 03:56 UTC, voscarmv approved these changes
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-01-06 14:02 UTC, merged